config/routes.rb
Rails.application.routes.draw do
  resources :barcodes do
    collection do
      post 'import'
    end
  end
  root 'barcodes#index'

end

app/models/barcode.rb
class Barcode < ActiveRecord::Base
  validates :id, uniqueness: true
  self.primary_key = 'id'
  #before_create :create_product

  has_one :product, foreign_key: "Prod_Num"
  has_one :price, foreign_key: "ProdNum"
  has_one :itemfile, foreign_key: "UPC_GTIN"
  #has_one :alp_product, foreign_key: "Prod_Num"

  def self.fieldlize(name)
      return name.gsub(/[^a-zA-Z\d]/, '_')
  end

  def self.loadData(data)
    ct_create = 0
    ct_update = 0
    errors = []

    data.each do |record|
      attrs = {}
      klss = []
      record.each do |cell|
        fd = fieldlize(cell['n'])
        if fd == 'UPC_GTIN' then
          klss = [{'class_name'=>'Itemfile', 'key'=>fd}]
        end
        if fd == 'Prod_Num' then
          klss = [{'class_name'=>'Product', 'key'=>fd}, {'class_name'=>'Price', 'key'=>'ProdNum'}]
        end
        attrs[fd] = cell['v']
      end


      klss.each do |kls|
        column_names = kls['class_name'].constantize.send 'column_names'


        attrs[kls['key']] = attrs[kls['key']].gsub(/[^\d]/, '')
        next if attrs[kls['key']] == ''

        klass = Object.const_get kls['class_name']
        inst = kls['class_name'].constantize.send(:find_by, {kls['key'] => attrs[kls['key']]})

        if (inst == nil) then
          inst = klass.new
          ct_create = ct_create + 1
          debugger
        else
          ct_update = ct_update + 1
        end
        begin
          inst.update(attrs)
          inst.save
        rescue Exception => e
          attrs.each do |k, v|
            next if k == 'UPC_GTIN'
            trial = kls['class_name'].constantize.send(:find_by, {kls['key'] => attrs[kls['key']]})
            trial = klass.new if (trial == nil)
            trial_attrs = {'UPC_GTIN'=>attrs['UPC_GTIN'], k => v}
            begin
              trial.update(trial_attrs)
            rescue Exception => e2
              debugger
            end
          end
          debugger
          errors << "error: #{attrs['UPC_GTIN']} #{e.message}"
        end

      	barcode = Barcode.find_by({'id'=>attrs['UPC_GTIN']})
      	if barcode ==nil then
      		barcode = Barcode.new
      		barcode.id= attrs['UPC_GTIN']
      		barcode.save
      	end

      end


#      barcode = Barcode.find_by(id: attrs['UPC_GTIN'])
#      if barcode == nil then
#        barcode = Barcode.new
#        barcode.id = attrs['UPC_GTIN']
#        barcode.save
#      end
    end
    return {'created' => ct_create, 'updated' => ct_update, 'errors' => errors}
  end

end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  before_action :set_barcode, only: [:show, :edit, :update, :destroy]

  # GET /barcodes
  # GET /barcodes.json
  def index
    @barcodes = Barcode.paginate(:page => params[:page], :per_page => 100).order('id')
  end

  # GET /barcodes/1
  # GET /barcodes/1.json
  def show
    @readonly = !params.has_key?(:edit)
  end

  def import
    @result = Barcode.loadData(JSON.parse(params['records']))
    respond_to do |format|
      format.json
    end
  end

  # GET /barcodes/new
  def new
    @barcode = Barcode.new
  end

  # GET /barcodes/1/edit
  def edit
  end

  # POST /barcodes
  # POST /barcodes.json
  def create
    @barcode = Barcode.new(barcode_params)

    respond_to do |format|
      if @barcode.save
        format.html { redirect_to @barcode, notice: 'Barcode was successfully created.' }
        format.json { render :show, status: :created, location: @barcode }
      else
        format.html { render :new }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barcodes/1
  # PATCH/PUT /barcodes/1.json
  def update
    @obj = @barcode.send params['classname'].underscore

    obj_params = {}
    params.each do |k, v|
      obj_params[k] = v if !%w(classname commit action controller authenticity_token _method utf8).include?(k)
    end

    respond_to do |format|
      if @obj.update(obj_params)
        format.html { redirect_to @barcode, notice: 'Barcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @barcode }
      else
        format.html { render :edit }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barcodes/1
  # DELETE /barcodes/1.json
  def destroy
    @barcode.destroy
    respond_to do |format|
      format.html { redirect_to barcodes_url, notice: 'Barcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barcode
      @barcode = Barcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barcode_params
      params[:barcode].permit(:id)
    end
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
  def format(v, n)
    return '' if v == nil


    if v.class.to_s == 'String' then
      txt = v.to_s
      return txt if txt.encoding.to_s == 'UTF-8'
      return txt.encode('UTF-8') if txt.encoding.to_s == 'US-ASCII'
      debugger
      puts "unknown encoding: " + txt.encoding.to_s
    else
      return v.to_s
      #for debug only
      if !['Fixnum', 'BigDecimal', 'Float', 'TrueClass', 'FalseClass', 'ActiveSupport::TimeWithZone'].include?(v.class.to_s)
        puts "unknown class: " + v.class
      end
    end
  end
end

app/views/barcodes/_edit_table.html.erb
<%= form_for(@barcode) do |f| %>
  <%= hidden_field_tag 'classname', product.class%></td>

  <div class="btn-toolbar pull-right">
    <a href="?edit" class="btn btn-primary">Edit</a>
    <%= f.submit disabled: readonly, class: 'btn btn-primary'%>
  </div>

  <table class='table table-striped table-condensed'>
    <thead>
      <tr><th colspan='2'><%=product.class.to_s.gsub('Product', 'Product')%></th></tr>
    </thead>

    <tbody>
      <% product.class.column_names.each do |cn| %>
        <tr>
          <td><%= cn %></td>
          <td><%= text_field_tag cn, format(product[cn], cn), disabled: readonly%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/barcodes/_form.html.erb
<%= form_for(@barcode) do |f| %>
  <% if @barcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barcode.errors.count, "error") %> prohibited this barcode from being saved:</h2>

      <ul>
      <% @barcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :id%>
    <%= f.submit %>
  </div>
<% end %>

app/views/barcodes/_table.html.erb
<table class='table table-striped table-condensed'>
<tr>
  <th colspan='2'><%=product.class.to_s.gsub('Product', 'Product')%></th>
</tr>

<% product.class.column_names.each do |cn| %>
  <tr>
    <td><%= cn %></td>
    <td><%= product[cn] %></td>
  </tr>
<% end %>
</table>

app/views/barcodes/edit.html.erb
<div class="container">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#product" role="tab" data-toggle="tab">Product</a></li>
      <li><a href="#price" role="tab" data-toggle="tab">Price</a></li>
      <li><a href="#itemfile" role="tab" data-toggle="tab">Itemfile</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane fade active in" id="product">
        <a href="?edit" class="btn btn-primary navbar-right">Edit</a>
        <%= render partial: "edit_table", locals: {readonly: true, product: @barcode.product} %>
      </div>
      <div class="tab-pane fade" id="price">
        <a href="?edit" class="btn btn-primary navbar-right">Edit</a>
        <%= render partial: "edit_table", locals: {readonly: true, product: @barcode.price} %>
      </div>
      <div class="tab-pane fade" id="itemfile">
        <a href="?edit" class="btn btn-primary navbar-right">Edit</a>
        <%= render partial: "edit_table", locals: {readonly: true, product: @barcode.itemfile} %>
      </div>
    </div>
</div>

app/views/barcodes/import.html.erb
<%=react_component('ParseExcel', tokenName: request_forgery_protection_token, token: form_authenticity_token)%>

app/views/barcodes/index.html.erb
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
<table class='table table-striped table-condensed'>
  <thead>
    <tr>
      <th>Barcode</th>
      <th>Item Description</th>
      <th>Item Price</th>
    </tr>
  </thead>

  <tbody>
    <% @barcodes.each do |barcode| %>
      <tr>
        <td><%= barcode.id %></td>
        <td><%= barcode.itemfile.Item_Description_1 %></td>
        <td><%= barcode.itemfile.Base_Unit_Retail %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>

<%= react_component('Upload', tokenName: request_forgery_protection_token, token: form_authenticity_token)%>

app/views/barcodes/new.html.erb
<h1>New barcode</h1>

<%= render 'form' %>

<%= link_to 'Back', barcodes_path %>

app/views/barcodes/show.html.erb
<div class="container">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#itemfile" role="tab" data-toggle="tab">Itemfile</a></li>
      <li><a href="#product" role="tab" data-toggle="tab">Product</a></li>
      <li><a href="#price" role="tab" data-toggle="tab">Price</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane fade active in" id="itemfile">
        <%= render partial: "edit_table", locals: {readonly: @readonly, product: @barcode.itemfile} %>
      </div>
      <div class="tab-pane fade" id="import">
        <%= react_component('Upload', label: 'John') %>
      </div>
    </div>

    <div class="tab-content">
      <div class="tab-pane fade" id="product">
        <%= render partial: "edit_table", locals: {readonly: @readonly, product: @barcode.product} if @barcode.product != nil %>
      </div>
    </div>

    <div class="tab-content">
      <div class="tab-pane fade" id="price">
        <%= render partial: "edit_table", locals: {readonly: @readonly, product: @barcode.itemfile} %>
      </div>
    </div>

</div>